codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false
flags:
  unittests:
    carryforward: true
    paths:
      - FeedCord/src
coverage:
  precision: 2
  range: "80...100"
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: false
    project: false
slack_app: true
